set:
  features: false
  train: false
  eval: true

path:
  root_dir:  /home/perretty/Task5/dcase-few-shot-bioacoustic/baselines/deep_learning/Root
  train_dir: /home/perretty/Task5/dcase-few-shot-bioacoustic/Development_Set_Glider_v2/Training_Set/
  eval_dir:  /home/perretty/Task5/dcase-few-shot-bioacoustic/Development_Set_Glider_v2/Validation_Set/
  feat_path: ${path.root_dir}/Features_v2
  feat_train: ${path.feat_path}/feat_train
  feat_eval:  ${path.feat_path}/feat_eval
  Model: ${path.root_dir}/Model_v2
  best_model: ${path.Model}/best_model.pth
  last_model: ${path.Model}/last_model.pth

features:
  seg_len: 0.200
  hop_seg: 0.100
  eps: 2.220446049250313e-16
  fmax: 100
  fmin: 30
  sr: 22050
  n_fft: 1024
  n_mels: 128
  hop_mel: 256
  
train:
  num_classes: 5
  n_shot: 5
  k_way : 3
  device: cuda
  lr_rate: 0.0001
  scheduler_gamma: 0.5
  scheduler_step_size: 10
  epochs: 100
  num_episodes: 500
  encoder: Resnet  # Protonet or Resnet
eval:
  samples_neg: 50
  iterations: 10
  query_batch_size: 1 
  negative_set_batch_size : 1
  threshold: 0.45
